### ISSUE TITLE
Clamav rpm create on Centos 6

### ISSUE THREAD

**Issue by WolfgangT71** [leifliddy/podman-clamav-el6#1]
Hallo ich denke du kannst Deutsch. Wie kann ich die el6 rpms auf einem Centos6 server erstellen? dnf geht nicht mehr einfach, somit sind deine Instruktionen nicht leicht zu folgen. ebenfalls python3 ist nicht vorhanden, habe nur python 2.6.6-29. Oder gibt es irgendwo eine Möglichkeit die fertigen RPM's zu bekommen?

Gruß Wolfgang

**Comment by leifliddy** [comment]
This project uses a (centos6) podman container to build the el6 rpms. 

My instructions show how to build and run this container on a Fedora system   
You would need to ensure these packages were installed 
```dnf install podman python3-podman python3-termcolor```
and then run ```./script-podman.py --auto``` to build the rpms. 

But you could easily modify things to run on almost any moden Linux distro.   
You could manually build an image from the `Containerfile` and run it. 


The instructions for how to build the rpms are located in the `Containerfile` and `01-build.clamav.rpm.sh`
You see exactly how it's working. 

To build the rpms on a centos6 system you could just do the following.
```
wget https://github.com/leifliddy/podman-clamav-el6/blob/master/files/clamav-0.103.4-1.el6.src.rpm
yum-builddep -y clamav-0.103.4-1.el6.src.rpm
rpm -ivh clamav-0.103.4-1.el6.src.rpm
rpmbuild -ba /root/rpmbuild/SPECS/clamav.spec
```
You can then find the rpms here: 
```
[root@clamav_builder ~]# find /root/rpmbuild/RPMS/ -type f 
/root/rpmbuild/RPMS/x86_64/clamav-0.103.4-1.el6.x86_64.rpm
/root/rpmbuild/RPMS/x86_64/clamav-lib-0.103.4-1.el6.x86_64.rpm
/root/rpmbuild/RPMS/x86_64/clamav-devel-0.103.4-1.el6.x86_64.rpm
/root/rpmbuild/RPMS/x86_64/clamav-update-0.103.4-1.el6.x86_64.rpm
/root/rpmbuild/RPMS/x86_64/clamd-0.103.4-1.el6.x86_64.rpm
/root/rpmbuild/RPMS/x86_64/clamav-milter-0.103.4-1.el6.x86_64.rpm
/root/rpmbuild/RPMS/x86_64/clamav-debuginfo-0.103.4-1.el6.x86_64.rpm
/root/rpmbuild/RPMS/noarch/clamav-filesystem-0.103.4-1.el6.noarch.rpm
```

I don't like to provide compiled RPMs. 
It's much better security-wise to just provide the source.

**Comment by WolfgangT71** [comment]
Thanks, of course you are right with providing the source, I installed a fedora system in VBOX on my debian system, and it just now I finished everything.
Install was not straight forward, but after uinstall old clamav it was easy, should now work. Thanks used your centos6 instructions directly as I was missing libpcre2-8 when installing from the created rpms.
